layout: sidebar
style: dark
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
permalink: '/:year/:month/:day/:title/'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: null
social_media:
  facebook: sowderca
  instagram: sowderca
  linkedin: sowderca
  website: 'http://sowder.io'
  youtube: sowderca
topics:
  - name: PowerShell
    web_url: 'https://github.com/topics/powershell'
    image_url: >-
      https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/powershell/powershell.png
  - name: .NET
    web_url: 'https://github.com/topics/dotnet'
    image_url: >-
      https://raw.githubusercontent.com/github/explore/93d8a67084f94b2a444e510199a6e7622e5b09a3/topics/dotnet/dotnet.png
  - name: React
    web_url: 'https://github.com/topics/react'
    image_url: >-
      https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png
  - name: TypeScript
    web_url: 'https://github.com/topics/typescript'
    image_url: >-
      https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png
  - name: Azure
    web_url: 'https://github.com/topics/azure'
    image_url: >-
      https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/azure/azure.png
